# jeffcoin task-readme-github-pages.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.19

inputs:
- name: jeffcoin

outputs:
- name: jeffcoin-updated

run:
  path: ./jeffcoin/ci/scripts/readme-github-pages.sh
  # args: [-debug]
